[project]
name = "illustrated-japanese-words-and-conversations-for-every-day"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cchooks>=0.1.5",
    "genanki>=0.13.1",
]
